listener 1883 127.0.0.1
protocol mqtt
allow_anonymous true

listener 9001 0.0.0.0
protocol websockets
allow_anonymous true

log_type all
log_dest stdout

persistence true
persistence_location C:\Program Files\mosquitto\data\

max_packet_size 65536
message_size_limit 65536